### ISSUE TITLE
main.py to use parameters/flags to use either fake or actual AIs

### ISSUE THREAD

**Issue by lpabon** [aipresenter/aipresenter#37] opened 2023-06-22 14:14 UTC

**Comment by lpabon** [comment] 2023-06-22 19:07
see https://github.com/lpabon/ghstats/blob/master/ghstats.py#L113-L121

**Comment by lpabon** [comment] 2023-06-29 13:09
What we want is: `python3 main.py --script=myscript.yml`

We can then also do`python3 main.py --help`

**Comment by immanuelpabon** [comment] 2023-07-05 12:50
duplicate of #51

**Closed by immanuelpabon** 2023-07-05 12:50 UTC
